### ISSUE TITLE
PDF Unity guides

### ISSUE THREAD

**Issue by JoshuaBridgeman** [PlaceholderGames/2ndYearHelpDesk#23]
A few weeks ago I downloaded a game development humble bundle which contained various guides for different engines, since I bought it I thought I would share it since the bundle will never be available again for several years

link to the pdf's on my MEGA storage, contact me if the link breaks or has broken

https://mega.nz/#F!ObxGiIAC!b1w9TrORhDWjSoUPwR25wg

**Comment by DoctorMikeReddy** [comment]
It's the £5 request that makes this illegal. In UK law, copyright abuse depends on there being a profit. If you want to share files, I cannot stop you. However, the idea of being compensated makes this a problem, Josh. Can I suggest that you delete the link?
