### ISSUE TITLE
Github video footage upload

### ISSUE THREAD

**Issue by MolnarSyrus** [PlaceholderGames/2ndYearHelpDesk#25]
To any other team that has video footage on their Github issues, how do you do the whole thing generally? What program do you use to capture the footage, do you edit it in any shape or form, and what type of file do you upload in the end? Is it a GIF, if yes what program do you use to make that? 
I've been having a lot of trouble with this, and although I did find a way to do it, I'm sure there's much better methods to go about it.

Thanks for the help!

**Comment by SheDemon** [comment]
You can easily use OBS or I think you should be able to capture video with nVidia experience

**Comment by MolnarSyrus** [comment]
I know it seems like an obvious answer but Nvidia experience doesn't work with my laptop, and you can't upload .flv files (what OBS gives you) on github.

**Comment by DewyHealy** [comment]
You could just upload it to YouTube unlisted and embed it in a GitHub post.

**Comment by 16079892** [comment]
I use a program called ScreenToGif which works really well if you only want to show a smaller clip. Although It's probably best to upload and link to you tube if you have anything too long for a GIF.
