### ISSUE TITLE
Logic for the level/game

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2ndYearHelpDesk#8]
Does anyone know if the level logic must be done in the level blueprint, or can it be done somewhere else? Perhaps in the GameMode blueprint?

**Comment by AdamScott121** [comment]
For level logic, it done within the level blueprints Event Graph. 

As everything is kinda of auto encapsulated any modifications are additional logic must be made direct to specific blueprint. 

Gamemode blueprints are used for creating well gamemodes. You kinda wouldn't want Capture the Flag to have the same logic for Deathmatch.

**Comment by BojanStankovic** [comment]
It is not quite true that "additional logic must be made direct to specific blueprint" - @AdamScott121 . Please take a look at this document: https://docs.unrealengine.com/latest/INT/Engine/Blueprints/UserGuide/BlueprintCommsUsage/

Also, GameMode can be used for any logic and it is up to a developer what they use it for. The example you provided is certainly not true for a game like World of Tanks Blitz where for the same level you have multiple types of winning scenarios plus the ability to use the map as a training ground. In that case you'd want the GameMode to handle the logic.

Let me reformulate the question:
Did anyone succeeded on putting the level logic somewhere else instead into the level blueprint? If not, does anyone know how to do it? It is required in order to implement Macros for levels in the similar fashion as it can be done for all other blueprints that have specified parent class. See #7

**Comment by DoctorMikeReddy** [comment]
Remember the duck. There are many ways to do things, some more valid than others; some will be the best for particular situations, which is usually common sense. Go for what is simplest.
