### ISSUE TITLE
Third person look up with Spine

### ISSUE THREAD

**Issue by LiamVallance** [PlaceholderGames/2ndYearHelpDesk#9]
I have a multiplayer first person shooter game with a third person model for the other players to see, i am trying to make it so that when the first person view looks up to shoot, the third person model looks up for the other players to see.

At the moment the entire model looks up (feet in the air like a plank). I am trying to have it so that looking up only affects the third person spine mesh rather than any other bone joint.

If anyone has worked this out or thinks they may have some information that may help it would be very appreciated.

Thanks,
Liam

**Comment by DoctorMikeReddy** [comment]
This is sorted now, I believe

**Comment by LiamVallance** [comment]
Yes, a work around was set in place
